apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"     
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000  # Grafana listens on port 3000
    protocol: TCP
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
