apiVersion: v1
kind: Service
metadata:
  name: app-loadbalancer-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # This specifies a Network Load Balancer
spec:
  selector:
    tier: app
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
